version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - db_test
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/BulletinBoard
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8080:8080"

  db:
    image: postgres:13.3
    container_name: db
    environment:
      POSTGRES_DB: "BulletinBoard"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5432:5432"

  db_test:
    image: postgres:13.3
    container_name: db_test
    environment:
      POSTGRES_DB: "BulletinBoardTest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

    ports:
      - "5433:5433"